#!/usr/bin/php 
<?php 

// change the working directory
define('WD', sprintf('%s/%s', $_SERVER['HOME'], 'v-agent'));

chdir(realpath(WD));

require __DIR__  . '/vendor/autoload.php';

use Dotenv\Dotenv;
use Symfony\Component\Process\Process;
use Symfony\Component\Console\Application;

// Commands
use Commands\ChangePanelUrl;
use Commands\ChangePanelToken;
use Commands\GetEnv;


$dotenv = Dotenv::create('.');
$dotenv->load();

$application = new Application();

// register command here.

$application->add(new ChangePanelUrl());
$application->add(new ChangePanelToken());
$application->add(new GetEnv());

$application->run();